source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# Security pins for transitive deps (MBL-1682 + MBL-1691)
gem 'activesupport', '8.0.4.1'
gem 'json', '2.10.2'
gem 'addressable', '2.9.0'
gem 'faraday', '1.10.5'
gem 'aws-sdk-s3', '1.208.0'
gem 'rexml', '3.4.2'

gem 'fastlane'
gem 'cocoapods'

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
