# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Automatically install local version of the iOS SDK if the iOS SDK source code is installed alongside the flutter SDK. 
  local_ios_sdk_install_path = File.expand_path(File.join('..', '..', '..', '..', "customerio-ios"), __FILE__)
  if Dir.exist?(local_ios_sdk_install_path)
    puts "Installing local version of the iOS SDK for convenient development. Path of iOS SDK: #{local_ios_sdk_install_path}"

    # These entries will override the dependencies found in the .podspec in this Flutter project. 
    pod 'CustomerIO/Tracking', :path => local_ios_sdk_install_path
    pod 'CustomerIO/MessagingInApp', :path => local_ios_sdk_install_path
    pod 'CustomerIO/MessagingPushFCM', :path => local_ios_sdk_install_path
  else 
    puts "Note: If you install the Customer.io iOS SDK source code to path #{local_ios_sdk_install_path}, the iOS example app will use that local version of the SDK for convenient local development."
  end
  
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
