###
# How to configure what version of the iOS SDK is installed on your machine. 
#
# This is the order of priority for installing:
# 
# 1. Install local version of CIO SDK, if the source code is found on your local computer. 
#    To enable this feature, pass environment variable with the path set to where on your computer the iOS SDK source code is. 
install_ios_sdk_local_path = ENV['INSTALL_IOS_SDK_LOCAL'] || nil 
# 2. Install from a CIO SDK git branch. 
#    To install from a branch, pass environment varible with branch name
install_ios_sdk_branch_name = ENV['INSTALL_IOS_SDK_BRANCH'] || nil 
# 3. Install version of CIO SDK specified in `/ios/customer_io.podspec` file. 
#
###

# All of the CIO pods that are listed as dependencies in `/ios/customer_io.podspec` need to be listed here in this array:
all_ios_pods_flutter_plugin_needs = [
  'CustomerIO/Tracking',
  'CustomerIO/MessagingInApp',
  'CustomerIO/MessagingPushFCM'
]

# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  if install_ios_sdk_local_path != nil then 
    puts ""
    puts "⚠️ Installing local version of the iOS SDK. Path of iOS SDK: #{install_ios_sdk_local_path}"
    puts ""

    all_ios_pods_flutter_plugin_needs.each { |podname| 
      pod podname, :path => install_ios_sdk_local_path
    }
  elsif install_ios_sdk_branch_name != nil then 
    puts ""
    puts "⚠️ Installing CIO iOS SDK from git branch #{install_ios_sdk_branch_name}"
    puts ""

    all_ios_pods_flutter_plugin_needs.each { |podname| 
      pod podname, :podspec => "https://raw.githubusercontent.com/customerio/customerio-ios/#{install_ios_sdk_branch_name}/CustomerIO.podspec"
    }
  end
  
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
