name: Setup 
description: Setup runner to be able to build an app with Flutter. Not specific for Android or iOS.

runs:
  using: "composite"
  steps:
  # Install latest stable version of Flutter. Mostly because k-paxian/dart-package-publisher always uses the latest stable version of Flutter and we want the rest of the CI to match that. 
  - uses: subosito/flutter-action@v2
    with:
      channel: 'stable'
      cache: true

  - run: flutter --version
    shell: bash 

  - name: Install Flutter dependencies
    run: flutter pub get
    shell: bash 
