name: Setup
description: Setup runner to be able to build an app with Flutter. Not specific for Android or iOS.

inputs:
  app_name:
    description: "Sample app directory name under apps/"
    required: false
    default: "flutter_sample_spm"

runs:
  using: "composite"
  steps:
  - uses: subosito/flutter-action@e938fdf56512cc96ef2f93601a5a40bde3801046 # v2.19.0
    with:
      channel: stable

  - run: flutter --version
    shell: bash

  - run: flutter clean
    shell: bash

  - name: Install Flutter dependencies
    run: flutter pub get
    shell: bash

  - name: Install Flutter dependencies for sample app
    run: |
      cd apps/${{ inputs.app_name }}
      # Create a dummy .env file to prevent analysis warnings.
      # This will be replaced by the real .env file in the prepare-for-app-build action.
      touch .env
      flutter pub get
    shell: bash
