name: Setup
description: Setup runner to be able to build an app with Flutter. Not specific for Android or iOS.

runs:
  using: "composite"
  steps:
  - uses: subosito/flutter-action@e938fdf56512cc96ef2f93601a5a40bde3801046 # v2.19.0
    with:
      channel: stable

  - run: flutter --version
    shell: bash

  - run: flutter clean
    shell: bash

  - name: Install Flutter dependencies
    run: flutter pub get
    shell: bash

  - name: Install Flutter dependencies for sample apps
    run: |
      for app_dir in apps/flutter_sample_*/; do
        echo "Installing dependencies for $app_dir"
        cd "$app_dir"
        touch .env
        flutter pub get
        cd -
      done
    shell: bash
