# Generate icons by running the following command
# dart run flutter_launcher_icons -f config/flutter_launcher_icons.yaml
flutter_launcher_icons:
  adaptive_icon_foreground: "assets/icon/icon_image.png"
  adaptive_icon_background: "#FFFFFF"
  android: "ic_launcher"
  image_path_android: "assets/icon/icon_image.png"
  image_path_ios: "assets/icon/icon_with_background.png"
  ios: true
  min_sdk_android: 21
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false
