name: Publish test apps for SDK release

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-primary-app:
    uses: ./.github/workflows/reusable-build-sample-apps.yml
    with:
      use_latest_sdk_version: true
      sample_app_name: flutter_sample_spm
      cio_workspace_name: "Mobile: Flutter"
      is_primary_app: true
    secrets: inherit
