name: Publish test apps for SDK release

on:
  workflow_dispatch:

jobs:
  build-sample-apps:
    uses: ./.github/workflows/reusable-build-sample-apps.yml
    with:
      use_latest_sdk_version: true
    secrets: inherit
