name: Check API Changes

on: [pull_request]

# Cancel jobs and just run the last one
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_api_changes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup-flutter
    
    - name: Check for API changes
      run: ./scripts/check_api_changes.sh
