name: Deploy git tag

# Only run after a pull request has been merged. This is because
# bot account runs write operations on the github repo to push a tag.
on:
  push:
    branches: [main]

permissions:
  contents: write # access to push the git tag
  issues: write # Bot creates an issue if there is an issue during deployment process
  pull-requests: write # allow bot to make comments on PRs after they get deployed

jobs:
  deploy-git-tag:
    name: Deploy git tag
    runs-on: ubuntu-latest
    outputs:
      new_release_git_head: ${{ steps.semantic-release.outputs.new_release_git_head }}
      new_release_published: ${{ steps.semantic-release.outputs.new_release_published }}
      new_release_version: ${{ steps.semantic-release.outputs.new_release_version }}
    steps:
      - uses: actions/checkout@v4

      # CLI to replace strings in files. The CLI recommends using `cargo install` which is slow. This Action is fast because it downloads pre-built binaries.
      # If using sd on macos, "brew install" works great. for Linux, this is the recommended way.
      - name: Install sd CLI to use later in the workflow
        # uses: kenji-miyake/setup-sd@v1
        uses: levibostian/setup-sd@add-file-extension # Using fork until upstream Action has bug fixed in it.

      - name: Deploy git tag via semantic release
        uses: cycjimmy/semantic-release-action@v4
        id: semantic-release
        with:
          semantic_version: latest
          extra_plugins: |
            conventional-changelog-conventionalcommits
            @semantic-release/github
            @semantic-release/exec
        env:
          # Needs to push git commits to repo. Needs write access.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify team of git tag being created
        uses: slackapi/slack-github-action@v1.26.0
        if: steps.semantic-release.outputs.new_release_published == 'true'
        with:
          # Use block kit to format the Slack message: https://app.slack.com/block-kit-builder
          payload: |
            {
              "text": "Flutter SDK git tag created",
              "username": "Flutter deployment bot",
              "icon_url": "https://img.icons8.com/color/512/flutter.png",
              "channel": "#mobile-deployments",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Flutter* SDK git tag created successfully! (deployment step 1 of 2)"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Version ${{ steps.semantic-release.outputs.new_release_version }}*\n\nFlutter SDK deployment progress:\n ~1. <https://github.com/${{github.repository}}/releases/tag/${{steps.semantic-release.outputs.new_release_version}}|create git tag>~\n2. deploy to pub.dev\n\n"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

      - name: Send Velocity Deployment
        uses: codeclimate/velocity-deploy-action@v1.0.0
        if: steps.semantic-release.outputs.new_release_published == 'true' # only run if a git tag was made.
        with:
          token: ${{ secrets.VELOCITY_DEPLOYMENT_TOKEN }}
          version: ${{ steps.semantic-release.outputs.new_release_version }}
          environment: production

      - name: Notify team of failure
        uses: slackapi/slack-github-action@v1.26.0
        if: ${{ failure() }} # only run this if any previous step failed
        with:
          # Use block kit to format the Slack message: https://app.slack.com/block-kit-builder
          payload: |
            {
              "text": "Flutter SDK deployment failure",
              "username": "Flutter deployment bot",
              "icon_url": "https://img.icons8.com/color/512/flutter.png",
              "channel": "#mobile-deployments",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Flutter* SDK deployment :warning: failure :warning:"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Flutter SDK failed deployment during step *create git tag*. View <https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}|CI server logs> to learn why and fix the issue. <https://github.com/customerio/mobile/blob/main/GIT-WORKFLOW.md|Learn more about the deployment process and how to fix errors>."
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
