name: Lint

on: [pull_request]

# Cancel jobs and just run the last one
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/setup-flutter
    - name: Run flutter analyze
      run: flutter analyze
    - name: Run dart analyze as deployment process also runs it
      run: dart analyze